// <auto-generated />
using System;
using Companies.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Companies.Data.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20221220155406_fixed seed data")]
    partial class fixedseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Companies.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OrganisationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SweCo",
                            OrganisationNumber = "2154516238"
                        });
                });

            modelBuilder.Entity("Companies.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Name = "Management"
                        });
                });

            modelBuilder.Entity("Companies.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool?>("IsUnionMember")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 3,
                            FirstName = "Lars",
                            IsUnionMember = false,
                            LastName = "Andersson",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            FirstName = "William",
                            IsUnionMember = true,
                            LastName = "Eklund",
                            Salary = 32000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Selma",
                            IsUnionMember = true,
                            LastName = "Wikström",
                            Salary = 35000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FirstName = "Adam",
                            IsUnionMember = false,
                            LastName = "Lundin",
                            Salary = 31500m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            FirstName = "Eva",
                            IsUnionMember = true,
                            LastName = "Nyberg",
                            Salary = 31000m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            FirstName = "Johan",
                            IsUnionMember = true,
                            LastName = "Blomqvist",
                            Salary = 34000m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            FirstName = "Anna",
                            IsUnionMember = true,
                            LastName = "Löfgren",
                            Salary = 29000m
                        });
                });

            modelBuilder.Entity("Companies.Data.Entities.EmployeeTitle", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("EmployeeTitles");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            TitleId = 5
                        },
                        new
                        {
                            EmployeeId = 2,
                            TitleId = 4
                        },
                        new
                        {
                            EmployeeId = 3,
                            TitleId = 6
                        },
                        new
                        {
                            EmployeeId = 4,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 5,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 5,
                            TitleId = 2
                        },
                        new
                        {
                            EmployeeId = 6,
                            TitleId = 1
                        },
                        new
                        {
                            EmployeeId = 6,
                            TitleId = 3
                        },
                        new
                        {
                            EmployeeId = 7,
                            TitleId = 7
                        });
                });

            modelBuilder.Entity("Companies.Data.Entities.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Database Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR Director"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 6,
                            Name = "IT Director"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Recruiter"
                        });
                });

            modelBuilder.Entity("EmployeeTitle", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("EmployeeTitle");
                });

            modelBuilder.Entity("Companies.Data.Entities.Department", b =>
                {
                    b.HasOne("Companies.Data.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Companies.Data.Entities.Employee", b =>
                {
                    b.HasOne("Companies.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Companies.Data.Entities.EmployeeTitle", b =>
                {
                    b.HasOne("Companies.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companies.Data.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("EmployeeTitle", b =>
                {
                    b.HasOne("Companies.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companies.Data.Entities.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companies.Data.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Companies.Data.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
